version: '2'
services:
  app: 
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "${APP_PORT}:80"
  node:
    extends:
      file: docker-compose.base.yml
      service: node
networks:
  sd-net:
    driver: "bridge"

