version: '2'
services:
  app:
    build: 
      context: ./docker/app
      dockerfile: Dockerfile
    image: shippingdocker.com/app
    volumes:
     - .:/var/www/html
    networks:
     - sd-net
    ports:
     - "${APP_PORT}:80"
  node:
    build: 
      context: ./docker/node
      dockerfile: Dockerfile
    image: shippingdocker.com/node
    volumes:
     - .:/var/www/html
    networks:
     - sd-net 
networks:
  sd-net:
    driver: "bridge"
